version: "2.4"
services:
  web:
    # the application's web service (container) will use an image based on our Dockerfile
    build: "."
    # map the internal port 80 to port 8000 on the host
    ports:
      - "8000:80"
    # map the host directory to app (which allows us to see and edit files inside the container)
    # /app assumes you're using that in the Dockerfile
    # /data is asuggestion for local media storage - see below
    volumes:
      - ".:/app:rw"

